### ISSUE TITLE
Steps to include core module unclear

### ISSUE THREAD

**Issue by Jan-PeterRichterCG** [devonfw/devonfw-tutorial-sources#11]
Category: enhancement

Severity: High

Description of issue / expected enhacement /Comments
On https://github.com/devonfw/devonfw-tutorial-sources/wiki/build-devon4ng-application there are several steps described to include a self-defined "core-module.ts" into other artefacts.
The description what to do is unclear.

> Remember that we need to import this module into the app.module the main app.component and every component of Angular Material and Covalent Teradata we use (i.e. for layouts it is CovalentLayoutModule). 

I understand that we have to 

1. import the core module to the app.module.ts file 
2. import the core module to the app.component.ts file
3. import the core module to every component of Angular Material and Covalent Teradata

- There is an example of how the app.modules.ts file should look like after the import. (fine!)
- There is **no** example of how the app.component.ts file should look like after the import. Adding the line `import { CoreModule } from './shared/core.module';` to the file results in a warning by Visual Studio Core: "'CoreModule' is declared but its value is never read."
- I have absolutely no idea, how I can " import this module into [...] every component of Angular Material and Covalent Teradata"

[Edit] hmmmm: I found an earlier version of this page. There, the sentence reads:

> Remember that we need to import in app.module the main app.component and every component
of Angular Material and Covalent Teradata we use [...].

So it is the app.component and the Angular Material and Covalent Teradata components that have to be imported into app.module.

Another Problem is the depicted file app.module.ts. It contains some lines that I cannot find in my file although I followed the instructions very closely. These lines are:
`import { HttpClientModule } from '@angular/common/http';`
`import 'hammerjs';`

This _may_ be a result of a failed `yarn add hammerjs` but even re-doing `yarn add hammerjs` does not produce any error messages and does not add these lines to app.module (and it is unclear to me whether I should use yarn to add these lines or have to add them manually.)
Where does the line `import { HttpClientModule } from '@angular/common/http';` come from? Do I have to add it manually?
When I look at core.module, I see `import { HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';` It is also (among many others) a member of the `exports` array but it is also the single member of the `providers` array. Question: (why) is it necessary to have the HttpClientModule in app.module when it is also in core.module? 

I also notice that my file contains `import { AppRoutingModule } from './app-routing.module';` and the `AppRoutingModule` in the `imports` array. This is probably a result of the option "Would you like to add Angular Routing" during the creation of the project. This is not part of the depicted app.module.ts

I am further puzzled by the note box below the depicted app.module.ts. It reads:

> Remember this step because you will have to repeat it for every other component from Teradata you use in your app.

As far as I have understood, the core.module is intended to _not_ need to include every other component from Teradata, or am I wrong? Are there "other" components that have not been included in core.module? If yes, please add a couple of examples for these components to be (manually) added.

Your environment - windows/Linux, Devonfw version , component
irrelevant

**Comment by trivesc** [comment]
Hello Jan-PeterRichterCG,

When the guide talks about importing the `CoreModule`, it means that in every component (that has a module) where you use either Angular Material or Covalent Teradata has to have the `CoreModule` imported on their module. If the component has no module, it will use the app module.

Concerning the `import { HttpClientModule } from '@angular/common/http';`: it is not needed since, we already import the `HttpClientModule` in the core. You can remove the import and the declaration inside `Imports: [`

Finally, `import 'hammerjs';` , this javascript library needs to be imported when gesture is being used. Yarn does not import it automatically, you need to add it manually.

I am sorry for the confusion and i will be fixing everything you have mentioned here and in the other issues as soon as possible.

Thanks for the feeback

**Comment by Jan-PeterRichterCG** [comment]
Hi trivesc,

I am currently in another attempt to learn more about devn4ng and Angular in general. I have only very little experience outside the java-based server domain, so everything (node.js / npm, angular CLI, typescript, ... and even HTML and JavaScript) is completely new to me.

Therefore, I am extremely easily confused by ambiguities in instruction texts and examples.

Please be tolerant if my issues are to nitpicky.

**Comment by trivesc** [comment]
Hello Jan-PeterRichterCG,
It is better that your issues are nitpicky, that way, the guide can be improved to the point where there is no issues and everything is clear.

Thanks for the feedback

**Comment by trivesc** [comment]
Hello @Jan-PeterRichterCG ,
The CoreModule explanation has been changed to be more understandable. After adding the covalent and material libraries with yarn, the user sees this text:

> Angular Material and Covalent need the following modules to work: CdkTableModule, BrowserAnimationsModule and every Covalent and Material Module used in the application. These modules come from @angular/material, @angular/cdk/table, @angular/platform-browser/animations and @covalent/core. In futur steps a CoreModule will be created, this module will contain the imports of these libraries, this will avoid code repetition.

Also, after creating the CoreModule, a note was added and the text after it clarified: 
Note:
> This CoreModule has almost every module of the different components for Angular Material and Covalent Teradata if you decide to use a component that is not included here, you need to add the corresponding module of the component here.

Text: 
> Remember that we need to import this CoreModule module into the app.module and inside every module of the different components that use Angular Material and Covalent Teradata. If a component does not have a module, it will be imported in the AppModule and hence, have the CoreModule. Our app.module.ts should have the following content:

The extra import from HttpClientModule has been removed.

And finally, hammer-js has been added in an earlier step when adding the styles to avoid confusion.

> In the same file than previous step, the hammer library is going to be added. In order to do so, we add inside both "scripts" arrays (inside build and test) the minimified script:

i am gonna close this issue since it has been solved,

Thanks for the feedback and regards,
trivesc
