### ISSUE TITLE
Confusing comment with respect to saving entities

### ISSUE THREAD

**Issue by Jan-PeterRichterCG** [devonfw/devonfw-tutorial-sources#25]
Category: enhancement

Severity: Low 

Description of issue / expected enhacement /Comments
In https://github.com/devonfw/devonfw-tutorial-sources/wiki/devon4j-adding-custom-functionality#2-implementing-the-methods-in--ucmanagequeueimpl it is said (two times) in the code snippet:
```
   //Based on hibernate, the command save(Entity) is not required.

   //the queueEntity gets saved
  getQueueRepository().save(queueEntity);
```
why is `getQueueRepository().save(queueEntity)` called if it is not required?

Perhaps the author of the comment wanted to say something like "saving is not strictly required, but we call save anyway. This is done to make the code more readable."
This should be verified by the person who wrote the original comment "Based on hibernate..."

Your environment - windows/Linux, Devonfw version , component
irrelevant

**Comment by trivesc** [comment]
Hello @Jan-PeterRichterCG ,
Yes, when creating that commentary, it was meant in the next way: Even if hibernate does not explicitly need the save because it will be taken care by hibernate automatically, it is called explicitly to make it more readable. The comments has been changed to:

> Based on hibernate, the command save(Entity) is not strictly required, but it improves readability.

i am closing this issue since it has been solved,
thanks for the feedback and regards,
trivesc
